theme: jekyll-theme-minimal

title: [Giulia M. Dotti Sani]

logo: /giulias.png

github:
  is_project_page: false

github:
  repository_url:  " "
  
#description: [Giulia Maria Dotti Sani is Assistant Professor in the Department of Social and Political Sciences at the University of Milano]

